id: P008269
initial_creation_type: ocr
source_metadata:
  id: bdr:W21814
  title: གསུང་ཐོར་བུ། འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས། ༼རྒྱ་གར་བིརའི་པར་མ།༽
  author: ''
  volumes:
    e0d81dc388e54502b7bbadff3f4d22d6:
      image_group_id: I3564
      title: ''
      volume_number: 1
      total_pages: 914
      base_file: v001.txt
    fbc25841b80946298a3f9bd08c06d47c:
      image_group_id: I3565
      title: ''
      volume_number: 2
      total_pages: 910
      base_file: v002.txt
