id: P008269
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 19:21:12.524263
source_metadata:
  id: bdr:W21814
  title: གསུང་ཐོར་བུ། འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས། ༼རྒྱ་གར་བིརའི་པར་མ།༽
  author: ''
  volumes:
    e0d81dc388e54502b7bbadff3f4d22d6:
      image_group_id: I3564
      title: ''
      volume_number: 1
      total_pages: 914
      base_file: v001.txt
    fbc25841b80946298a3f9bd08c06d47c:
      image_group_id: I3565
      title: ''
      volume_number: 2
      total_pages: 910
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
