id: IC92DEBF0
legacy_id: P008269
ocr_import_info:
  bdrc_scan_id: W21814
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T09:20:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:43:03.248673+00:00'
last_modified: 2022-09-01 22:44:47.391031
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21814
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21814
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས། ༼རྒྱ་གར་བིརའི་པར་མ།༽
  author: རྫོང་གསར་མཁྱེན་བརྩེ ༠༢་འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.5552128016824502
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I3564:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3564
      total_pages: 914
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3564.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5700219507893156
    legacy_id: v001
  I3565:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3565
      total_pages: 910
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3565.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5418653112940032
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
