id: IC92DEBF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:25:55+00:00'
last_modified: '2022-06-08T08:22:16.849910+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21814
  title: གསུང་ཐོར་བུ། འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས། ༼རྒྱ་གར་བིརའི་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BBBF:
      image_group_id: I3564
      title: ''
      total_pages: 914
      order: 1
      base_file: BBBF.txt
    B383:
      image_group_id: I3565
      title: ''
      total_pages: 910
      order: 2
      base_file: B383.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
